### ISSUE TITLE
Win - V0010-QA1 - Warp Drive - Destinations Bug

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#223]
Summary

If I sit on the Bridge at the Conn Console it is not possible to go to Warp. The Point you have to klick differs every Time you try to bring up the Destination Menu... It's luck ti find the right Spot. Gary_Baggins seems to have run into the same issue. 

The Thing we have in common is that we shut down headbob mode as soon as we start to play. 

What is the expected correct behavior?

One should be able to Access the Destination Menu without the guessing game where exactly to click on the console (or sometimes even above the console)

Steps to reproduce

    turn off Head Bob
    leave Transporter Room
    go to Bridge
    sit down at the Conn
    try to Open the Destinations

Possible fixes
Maybe ita has something to do with the Camera Settings if Headbob Mode is off.

**Comment by harryingles** [comment]
# Confirmed Issue

***Further Testing***

Entering the bridge with either headbob ***ON*** or ***OFF*** causes the issue where the button position is incorrect, and this changes every time you, the player, sit down at the console.

The issue can be fixed by switching to the headbob ***ON*** from ***OFF*** or vice versa - At this point, the button position is correct on the console

The issue reappears every time the bridge map is reloaded, for example getting into the turbolift and moving to deck 6 and then returning will put the problem back as it was, not dependant on headbob settings.

**Comment by dapperrobotbear** [comment]
That's a weird one.

**Comment by Sciencekeeper** [comment]
Yeah sorry i always seem to find weird ones. Could you reproduce it @ Dapperrobotbear?

**Comment by dapperrobotbear** [comment]
Haven't tried yet. But my guess is the expected position of the pointer is different in non head bob mode, which honestly we'll probably get rid of at some point.

**Comment by Sciencekeeper** [comment]
@TheStrato this is thankfully fixed BUT @dapperrobotbear the Disco Mode Button on the Captains chair is behaving exactly like that. I can activate disco mode by klicking about 3 cm ABOVE the console (only when headbob is offline)

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
