### ISSUE TITLE
Win - V0010-QA1 - Deck 9 Turbolift Doors remain open

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#240]
**Summary**

Turbolift doors staying open on Deck 9

***What is the expected correct behavior?***

Should close when you are not near the Turbolift

**Steps to reproduce**

1.  Go to Deck 9
2.  Head to Central Corridor near 9 Forward 
3.  Enter and exit Turbolift.

Note: I see a clear layer of the door opening and closing. I also saw this in v0.09 as well
![20180311115245_1](https://user-images.githubusercontent.com/4651111/37255446-ec566af8-2522-11e8-8d9a-bece222c128f.jpg)
![20180311115807_1](https://user-images.githubusercontent.com/4651111/37255507-df440108-2523-11e8-8d9f-e6f5c565527b.jpg)
![20180311115939_1](https://user-images.githubusercontent.com/4651111/37255508-df567ffe-2523-11e8-8c91-9aa3266c4b0a.jpg)
![20180311120021_1](https://user-images.githubusercontent.com/4651111/37255509-df67b90e-2523-11e8-8e0d-9d1fdf80e428.jpg)

**Comment by harryingles** [comment]
# Confirmed Issue

***Further Testing***

I believe this is linked to #195 

The turbolifts that are affected by this issue seem to correspond with the turbolifts mentioned in issue #195 that have coordinates instead of names - I assume these doors are not supposed to open.

Also, @trekkeriii suggested that some of the turbolift stops don't work if you, the player, get into the lift through some of the stuck open doors - I haven't tested this myself but suspect it is linked.

**Comment by dapperrobotbear** [comment]
Reconfirm against QA2

**Comment by EazyCheeze1978** [comment]
Not fixed in QA2, unfortunately...

**Comment by dapperrobotbear** [comment]
:-/ bogus

**Comment by HPringles** [comment]
Bug Win Mac @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
