### ISSUE TITLE
V0010-QA1 Reflectivity of wall changes on angle

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#324]
**Summary**

The reflectivity of the wall parallel to the entrance of the arboretum changes from highly reflective to matte, depending on a slight change in the viewing angle. When turning the matte part moves along the wall in a very abrupt manner (seen partly in the upper left corner of the matte screenshot). This may be a ship-wide issue. It only seems to happen on the general High and Epic settings.

***What is the expected correct behavior?***

Matte walls at any angle. Unless you're going for a chrome look.

**Steps to reproduce**

1. Go to the arboretum turbolift stop
2. Make a right turn
3. Look at the wall on your right

**Relevant logs and/or screenshots**

![shiny](https://user-images.githubusercontent.com/37262529/37326402-a14d078e-2657-11e8-9258-0c04e8732760.png)
![matte](https://user-images.githubusercontent.com/37262529/37326404-a2b968ec-2657-11e8-9812-2ea6109f330b.png)

**Possible fixes**

Change the specular setting, or reflectivity of the material.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by jgbr** [comment]
This changes on Mac as you change the graphics settings and maybe also linked to graphics card. Using a MacBook Pro with a dedicated and integrated graphics has a far bigger impact on this. I know debate will rage about if the panels on the corridor walls were reflective, I think it is more a stylistic choice where software will call the shots of if reflection is on or off. I think a completely matte ship would look 'rather old school graphics' so its worth keeping them. Shadows and reflections play a part in the real world but I imagine on a studio set due to the camera equipment etc they would do everything to brighten the image but decrease reflections. [Imagine seeing the camera reflected or edge of set for example].

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
