### ISSUE TITLE
Turning Head bob off, turns your arms and body invisble

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#38]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

In first person mode, if you choose to turn off HEAD BOB, your entire body disappear except your hands.

![stage9 screenshot 2017 11 26 - 21 32 44 89](https://user-images.githubusercontent.com/33987322/33244120-def031b0-d2f1-11e7-94a7-f4aadb1933ed.png)
![stage9 screenshot 2017 11 26 - 21 32 59 15](https://user-images.githubusercontent.com/33987322/33244121-df0bdd02-d2f1-11e7-8d2f-30b5c44eea74.png)
![stage9 screenshot 2017 11 26 - 21 33 18 26](https://user-images.githubusercontent.com/33987322/33244122-df27265c-d2f1-11e7-85b5-c1cccb0e1c18.png)

**Comment by harryingles** [comment]
I might be wrong, but I think thats intentional

**Comment by jeppelykke** [comment]
hope not :D i hope and think it's because camera just place to far back, so its inside of the body.

**Comment by scragnog** [comment]
Nope. This is intentional. For headbob mode, if you see the body, you'll notice that your head doesn't sit exactly where it should be (because the camera is disconnected from the skeleton, to stop headbob). So we hide the head/body. However, we still want you to interact with objects, so the hands are still visible.

**Comment by Gary-Baggins** [comment]
Intentional game mechanic @TheStrato please close.
