### ISSUE TITLE
V0010-GM - Unreal engine crashes closing application.

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#405]
Unreal engine fault when shutting down game via close game menu option or window close.

Occurs every other time. 

[This on Mac].

LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 #0 at 0x7fff53ca4e3e

__pthread_kill Address = 0x7fff53ca4e3e (filename not found) [in libsystem_kernel.dylib]
abort Address = 0x7fff53c01312 (filename not found) [in libsystem_c.dylib]
__cxa_bad_cast Address = 0x7fff51bdcf8f (filename not found) [in libc++abi.dylib]
default_terminate_handler() Address = 0x7fff51bdd113 (filename not found) [in libc++abi.dylib]
Unknown() Address = 0x7fff52f67eab (filename not found) [in libobjc.A.dylib]
std::__terminate(void (*)()) Address = 0x7fff51bf87c9 (filename not found) [in libc++abi.dylib]
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) Address = 0x7fff51bf826d (filename not found) [in libc++abi.dylib]
std::__1::__throw_system_error(int, char const*) Address = 0x7fff51bcb7af (filename not found) [in libc++.1.dylib]
std::__1::mutex::lock() Address = 0x7fff51bbdc93 (filename not found) [in libc++.1.dylib]
GASingleton<gameanalytics::logging::GALogger>::sharedInstance() Address = 0x1072df429 (filename not found) [in Stage9]
gameanalytics::logging::GALogger::e(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Address = 0x1072e0a25 (filename not found) [in Stage9]
gameanalytics::threading::GAThreading::thread_routine(void*) Address = 0x107302e3e (filename not found) [in Stage9]
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), void*> >(void*) Address = 0x107303b1c (filename not found) [in Stage9]
_pthread_body Address = 0x7fff53de06c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff53de056d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff53ddfc5d (filename not found) [in libsystem_pthread.dylib]

**Comment by jgbr** [comment]
LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 #0 at 0x7fff53ca4e3e

__pthread_kill Address = 0x7fff53ca4e3e (filename not found) [in libsystem_kernel.dylib]
abort Address = 0x7fff53c01312 (filename not found) [in libsystem_c.dylib]
__cxa_bad_cast Address = 0x7fff51bdcf8f (filename not found) [in libc++abi.dylib]
default_terminate_handler() Address = 0x7fff51bdd113 (filename not found) [in libc++abi.dylib]
Unknown() Address = 0x7fff52f67eab (filename not found) [in libobjc.A.dylib]
std::__terminate(void (*)()) Address = 0x7fff51bf87c9 (filename not found) [in libc++abi.dylib]
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) Address = 0x7fff51bf826d (filename not found) [in libc++abi.dylib]
std::__1::__throw_system_error(int, char const*) Address = 0x7fff51bcb7af (filename not found) [in libc++.1.dylib]
std::__1::mutex::lock() Address = 0x7fff51bbdc93 (filename not found) [in libc++.1.dylib]
GASingleton<gameanalytics::logging::GALogger>::sharedInstance() Address = 0x110144429 (filename not found) [in Stage9]
gameanalytics::logging::GALogger::e(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Address = 0x110145a25 (filename not found) [in Stage9]
gameanalytics::threading::GAThreading::thread_routine(void*) Address = 0x110167e3e (filename not found) [in Stage9]
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), void*> >(void*) Address = 0x110168b1c (filename not found) [in Stage9]
_pthread_body Address = 0x7fff53de06c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff53de056d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff53ddfc5d (filename not found) [in libsystem_pthread.dylib]

**Comment by jgbr** [comment]
Does it on restart and quit.

LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x1030d65ab (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x1031d4c2d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x10319da54 (filename not found) [in Stage9]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x10323e271 (filename not found) [in Stage9]
FAsyncLoadingThread::Run() Address = 0x10323f8cf (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x1030f9b6a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x1030e7416 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff53de06c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff53de056d (filename not found) [in libsystem_pthread.dyl

**Comment by tenko23** [comment]
Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3


It doesn't do it every time for me - this is the first time on close (or any since v10 came out):...

LoginId:09039d78d94fe6e33ed6a2b4e63982d0
EpicAccountId:

 #0 at 0x7fff72d6ae3e

__pthread_kill Address = 0x7fff72d6ae3e (filename not found) [in libsystem_kernel.dylib]
abort Address = 0x7fff72cc7312 (filename not found) [in libsystem_c.dylib]
__cxa_bad_cast Address = 0x7fff70ca5f8f (filename not found) [in libc++abi.dylib]
default_terminate_handler() Address = 0x7fff70ca6113 (filename not found) [in libc++abi.dylib]
_objc_terminate() Address = 0x7fff72030a4f (filename not found) [in libobjc.A.dylib]
std::__terminate(void (*)()) Address = 0x7fff70cc17c9 (filename not found) [in libc++abi.dylib]
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) Address = 0x7fff70cc126d (filename not found) [in libc++abi.dylib]
std::__1::__throw_system_error(int, char const*) Address = 0x7fff70c947af (filename not found) [in libc++.1.dylib]
std::__1::mutex::lock() Address = 0x7fff70c86c93 (filename not found) [in libc++.1.dylib]
GASingleton<gameanalytics::logging::GALogger>::sharedInstance() Address = 0x109368429 (filename not found) [in Stage9]
gameanalytics::logging::GALogger::e(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Address = 0x109369a25 (filename not found) [in Stage9]
gameanalytics::threading::GAThreading::thread_routine(void*) Address = 0x10938be3e (filename not found) [in Stage9]
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), void*> >(void*) Address = 0x10938cb1c (filename not found) [in Stage9]
_pthread_body Address = 0x7fff72ea66c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff72ea656d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff72ea5c5d (filename not found) [in libsystem_pthread.dylib]

**Comment by kaadaq** [comment]
I'm getting a crash message in Windows every time I close.
![image](https://user-images.githubusercontent.com/34050343/37793060-f8b7c1e2-2de3-11e8-8d22-21faab238724.png)

This is, no associated crash files are created.   I only get this when exiting the program via the Esc-menu "Quit" button.   If I exit via Alt-F4, I get no error.

Athlon XP CPU, 8GB RAM, Win 10

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
