### ISSUE TITLE
Seperate saucer and remote open shuttle bay 2 and then shuttle bay one 

### ISSUE THREAD

**Issue by tuvok2018** [dapperrobotbear/Stage9#424]
As above

**Steps to reproduce**

1.Seperate the saucer whilst in a shuttle and wait for it to depart 
2.Select remote open of shuttle bay 2
3.Select remote open of shuttle bay 1
4. Watch as shuttlebay appears on top of stardrive even though saucer is seperated
**Relevant screenshots**

![main shuttlebay bug](https://user-images.githubusercontent.com/36381392/37628350-0d378b58-2bd1-11e8-8c25-209a488e395e.jpg)

**Comment by kaadaq** [comment]
Possibly related to #73?

**Comment by tenko23** [comment]
Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

Yeah, it's there for a moment, although it disappears.....

![screen shot 2018-03-19 at 8 57 04 pm](https://user-images.githubusercontent.com/34230416/37631549-2ca56b5e-2bb8-11e8-8d2a-4b780365f0ff.jpg)

**Comment by jeppelykke** [comment]
For V0010 HF1 windows its there for a second as well, but one shuttle remains hovering above the drive section. 

![stage9 screenshot 2018 03 20 - 19 55 49 74](https://user-images.githubusercontent.com/33987322/37676642-c22e9806-2c78-11e8-9cf7-1f6c672f5e0b.png)

**Comment by kaadaq** [comment]
Unable to validate OP's sequence in V0010-HF1 because if you launch from the MSB, you have to remote open SB2 before you can click separate.  (Can't do Step 1 before Step 2).   If you launch from SB2, you can't do Step 2 at all, because it's already open.

That said, I *did* launch from SB2, remote open 1, then remote open 2, and then hit separate.   SB1 door opened with the bay despawned (similar to #73), but SB2 door also remained closed, leaving me effectively Lost in Space.   @Strato, not sure how you want to proceed on this.

**Comment by kaadaq** [comment]
@TheStrato, see above.   Unable to validate original issue, but identified a related problem.

**Comment by mzeppenfeld** [comment]
A few similar issues:
------------------------
Issue 1 (from fresh start):
1. Launched shuttle from Main Shuttlebay and flew around.
2. Opened Shuttlebay 2 from shuttle console.
3. Accidently jumped out of shuttle & landed on hull. (I couldn't get back into the shuttle bay due to force field)
4. Opened menu and used Emergency Transport.

I was transported to a turbolift with no surrounding corridors. Had to restart the game because I couldn't use the turbolift. See screenshots. I also have a video of this if you cannot recreate.

Result:
![1](https://user-images.githubusercontent.com/18473024/37877586-63e6cb54-302b-11e8-8676-e75d1d73676e.png)
![2](https://user-images.githubusercontent.com/18473024/37877587-63f182e2-302b-11e8-8f2f-51e8049293a2.png)
------------------------
Issue 2 (from fresh start):
1. Turbolifted to Main Shuttlebay.
2. Jumped in shuttle and clicked area where "Open Shuttlebay 1" would normally appear. It activated even though the button was not visible.
3. Flew out of the shuttlebay. The Enterprise never appeared.

See attached video in ZIP.
[shuttlebay.zip](https://github.com/dapperrobotbear/Stage9/files/1845575/shuttlebay.zip)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
